## Frame Parameters
ROBOT_FRAME: "robot_1/base_link"

# Robot Size Parameters
ROBOT_RADIUS: 0.35       # [m], If param "USE_FOOTPRINT" is set to true, this param is not used
FOOTPRINT_PADDING: 0.01 # [m], If localmap contains padding, you should set this param to 0.0

# Robot Configuration Parameters
MAX_VELOCITY: 1.0         # [m/s]
MIN_VELOCITY: -1.0         # [m/s]
MAX_YAWRATE: 3.14       # [rad/s]
MIN_YAWRATE: -3.14         # [rad/s]
MAX_IN_PLACE_YAWRATE: 0.6 # [rad/s]
MIN_IN_PLACE_YAWRATE: -0.6 # [rad/s]
MAX_ACCELERATION: 1.0     # [m/s^2]
MAX_DECELERATION: 3.0     # [m/s^2]
MAX_D_YAWRATE: 3.2        # [rad/s^2]
